export const RECOMMENDATION_CONFIG = {
  MAX_HISTORY_ITEMS: 20,
  MAX_RECOMMENDATIONS: 3,
  CATEGORY_WEIGHT: 0.6,
  TAG_WEIGHT: 0.3,
  RECENCY_WEIGHT: 0.1,
  MAX_AGE_DAYS: 30,
  MIN_RECOMMENDATIONS: 1,
} as const

export const RECOMMENDATION_ALGORITHM = {
  USE_CATEGORIES: true,
  USE_TAGS: true,
  USE_RECENCY: true,
  USE_PERSONALIZATION: true,
  FALLBACK_TO_POPULAR: true,
} as const

export const ANALYTICS_CONFIG = {
  TRACK_CLICKS: true,
  TRACK_IMPRESSIONS: true,
  SESSION_DURATION_MS: 30 * 60 * 1000,
  CTR_CALCULATION_WINDOW: 7 * 24 * 60 * 60 * 1000,
  STORE_LOCALLY: true,
  SEND_TO_ANALYTICS: false,
} as const