export const TELEMETRY = {
  RECENT_EVENT_COUNT: 10,
} as const

export const PARSING = {
  BASE64_RADIX: 10,
  DECIMAL_RADIX: 10,
} as const

export const MEMORY = {
  BYTES_TO_KB: 1024,
  BYTES_TO_MB: 1024 * 1024,
  BYTES_TO_GB: 1024 * 1024 * 1024,
  BYTES_PER_CHARACTER_UTF16: 2,
  PER_ENTRY_OVERHEAD_BYTES: 24,
  PER_DEPENDENCY_ENTRY_BYTES: 50,
  PER_DEPENDENT_ENTRY_BYTES: 50,
} as const

export const CACHE_METRICS = {
  HIGH_EFFICIENCY_THRESHOLD: 80,
  MEDIUM_EFFICIENCY_THRESHOLD: 50,
  MEMORY_ROUNDING_FACTOR: 100,
  MILLISECONDS_TO_SECONDS: 1000,
} as const

export const RATE_LIMIT = {
  DEFAULT_WINDOW_MS: 60000,
  HEALTH_MAX_REQUESTS: 300,
  READINESS_MAX_REQUESTS: 300,
  METRICS_MAX_REQUESTS: 60,
  CACHE_MAX_REQUESTS: 10,
  CSP_REPORT_MAX_REQUESTS: 30,
  DEFAULT_RETRY_AFTER_SECONDS: 60,
} as const
